services:
  - type: web
    name: anonymous-messages
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 8080
      - key: SECRET_KEY
        value: your_secret_key 